# fly.toml app configuration file generated for api-financas-full on 2026-02-28T15:24:23Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-financas-full'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 3333
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory_mb = 512
  cpu_kind = 'shared'
  cpus = 1

